# Default setup is given for MySQL with ruby1.8. If you're running Redmine
# with MySQL and ruby1.9, replace the adapter name with `mysql2`.
# Examples for PostgreSQL and SQLite3 can be found at the end.

{%- for app in pillar.redmine.server.apps %}
{%- if app_name == app.name %}
production:
  adapter: {{ app.database.engine }}
  {%- if app.database.dataserver is defined %}
  dataserver: {{ app.database.dataserver }}
  {%- endif %}
  database: {{ app.database.name }}
  host: {{ app.database.host }}
  username: {{ app.database.user }}
  password: "{{ app.database.password }}"
  encoding: utf8
{%- if app.database.enviroment is defined and app.database.enviroment == "test" %}
test:
  adapter: {{ app.database.engine }}
  {%- if app.database.dataserver is defined %}
  dataserver: {{ app.database.dataserver }}
  {%- endif %}
  database: {{ app.database.name }}
  host: {{ app.database.host }}
  username: {{ app.database.user }}
  password: "{{ app.database.password }}"
  encoding: utf8
{%- elif app.database.enviroment is defined and app.database.enviroment == "development" %}
development:
  adapter: {{ app.database.engine }}
  {%- if app.database.dataserver is defined %}
  dataserver: {{ app.database.dataserver }}
  {%- endif %}
  database: {{ app.database.name }}
  host: {{ app.database.host }}
  username: {{ app.database.user }}
  password: "{{ app.database.password }}"
  encoding: utf8
{%- endif %}
#development:
#  adapter: mysql
#  database: redmine_development
#  host: localhost
#  username: root
#  password: ""
#  encoding: utf8

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

#test:
#  adapter: mysql
#  database: redmine_test
#  host: localhost
#  username: root
#  password: ""
#  encoding: utf8

#test_pgsql:
#  adapter: postgresql
#  database: redmine_test
#  host: localhost
#  username: postgres
#  password: "postgres"

#test_sqlite3:
#  adapter: sqlite3
#  database: db/test.sqlite3

{%- endif %}
{%- endfor %}
